### ISSUE TITLE
ui5-middleware-serveframework + ui5-test-runner issue?

### ISSUE THREAD

**Issue by wozjac** [ArnaudBuchholz/ui5-test-runner#107]
Hi,

I noticed that test-runner fails if `ui5-middleware-serveframework` is used.

1. Go to https://github.com/SAP/openui5-sample-app
2. Add to `ui5.yaml`

```yaml
...
server:
  customMiddleware:
    - name: ui5-middleware-serveframework
      afterMiddleware: compression

    - name: "@ui5/middleware-code-coverage"
      afterMiddleware: compression
      configuration:
        excludePatterns:
          - "resources/"
          - "test/"
```

**Expected behavior**
Test runner executes.

**Report**
```sh
Died on test #1     at http://localhost:8080/resources/sap/ui/test/starter/runTest.js:1112:6559: Called start() while test already started running     
⠙ Generating reports
Error: Command failed with exit code 4294967295: npm run test-runner                                                                                   
    at makeError (C:\workspace\samples\openui5-sample-app\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\workspace\samples\openui5-sample-app\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 4294967295: npm run test-runner',
  command: 'npm run test-runner',
  escapedCommand: '"npm run test-runner"',
  exitCode: 4294967295,
```

BR,
Jacek
