### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by bawaji94** [ArnaudBuchholz/ui5-test-runner#115]
Hello,

I am trying to run the unit tests in gitlab-ci pipeline (trying to move away from karma-ui5 since it is deprecated) with the following `.gitlab-ci.yml` configuration

```yaml
unit-test:
  image: <docker-image-with-node-v20-installed>
  stage: test
  allow_failure: false
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm install
    - apk add --no-cache chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm run test:ci
```

`npm run test:ci` in turn runs the following command

```bash
ui5-test-runner --coverage --url http://localhost:8081/test/unit/unitTests.qunit.html --port 8081
```

`ui5-test-runner.json` has the following configuration

```json
{
    "coverageReporters": [
        "html",
        "text",
        "text-summary",
        "cobertura",
        "lcovonly"
    ]
}
```

And I am getting the following error

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/4bbefa05-8e40-4565-8449-efddb9357878" />

**Comment by ArnaudBuchholz** [comment]
Thanks for reporting the issue : as per the error message, did you check https://pptr.dev/troubleshooting page ?

I would also suggest `PUPPETEER_SKIP_DOWNLOAD` as documented here : https://arnaudbuchholz.github.io/ui5-test-runner/puppeteer/#implementation-notes

In any case, this problem is related to executing puppeteer in your environment, not directly to `ui5-test-runner`.

**Comment by bawaji94** [comment]
I was able to resolve it by providing the path to the chromium binary using `--binary` option, my `.gitlab-ci.yml` now is as below 

```
unit-test:
  image: <docker-image-with-node-v20-installed>
  stage: test
  allow_failure: false
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm install
    - apk add --no-cache chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
    - npm run test:ci -- -- --binary $CHROME_BIN
```
